spring.application.name=skillGapAnalysis

gemini.api.key=AIzaSyB8iBGb4UzdhABNZbHWQ6M72uLwfLAR-CE

spring.datasource.url=jdbc:mysql://mysql-3bc32d89-myproject20251807.k.aivencloud.com:20370/defaultdb?ssl-mode-REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_lXEn4u1J2sv85EZcilz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
